import { useState } from 'react'
import { aiApi } from '../api/aiApi'
import toast from 'react-hot-toast'
import './AiAssistPanel.css'

const AI_MODES = [
    { id: 'clarity', label: '✨ Improve Clarity', desc: 'Simplify and clarify your writing' },
    { id: 'grammar', label: '📝 Fix Grammar', desc: 'Correct grammar and punctuation' },
    { id: 'concise', label: '✂️ Make Concise', desc: 'Remove fluff, keep the core' },
]

export default function AiAssistPanel({ content, title, onApplyContent, onApplyTitle, onApplySummary, onApplyTags, category }) {
    const [activeMode, setActiveMode] = useState('clarity')
    const [loadingImprove, setLoadingImprove] = useState(false)
    const [loadingTitle, setLoadingTitle] = useState(false)
    const [loadingSummary, setLoadingSummary] = useState(false)
    const [loadingTags, setLoadingTags] = useState(false)
    const [suggestedTags, setSuggestedTags] = useState([])
    const [isOpen, setIsOpen] = useState(true)

    const handleImprove = async () => {
        const plainText = content ? content.replace(/<[^>]*>/g, '').trim() : ''
        if (plainText.length < 20) {
            toast.error('Please write at least 20 characters before using AI improve')
            return
        }
        setLoadingImprove(true)
        try {
            const data = await aiApi.improveContent(content, activeMode)
            onApplyContent(data.improvedContent)
            toast.success('✨ Content improved by AI!')
        } catch {
            toast.error('AI service unavailable. Please ensure backend is running.')
        } finally {
            setLoadingImprove(false)
        }
    }

    const handleSuggestTitle = async () => {
        const plainText = content ? content.replace(/<[^>]*>/g, '').trim() : ''
        if (plainText.length < 20) {
            toast.error('Write some content first so AI can suggest a title')
            return
        }
        setLoadingTitle(true)
        try {
            const data = await aiApi.suggestTitle(content)
            onApplyTitle(data.suggestedTitle)
            toast.success('💡 Title suggestion applied!')
        } catch {
            toast.error('AI service unavailable')
        } finally {
            setLoadingTitle(false)
        }
    }

    const handleGenerateSummary = async () => {
        const plainText = content ? content.replace(/<[^>]*>/g, '').trim() : ''
        if (plainText.length < 20) {
            toast.error('Write some content first')
            return
        }
        setLoadingSummary(true)
        try {
            const data = await aiApi.generateSummary(content, title)
            onApplySummary(data.summary)
            toast.success('📋 Summary generated by AI!')
        } catch {
            toast.error('AI service unavailable')
        } finally {
            setLoadingSummary(false)
        }
    }

    const handleSuggestTags = async () => {
        setLoadingTags(true)
        try {
            const data = await aiApi.suggestTags(content, category || 'TECH')
            setSuggestedTags(data.suggestedTags)
            toast.success('🏷️ Tags suggested by AI!')
        } catch {
            toast.error('AI service unavailable')
        } finally {
            setLoadingTags(false)
        }
    }

    const applyTag = (tag) => {
        onApplyTags(tag)
        setSuggestedTags(prev => prev.filter(t => t !== tag))
        toast.success(`Tag "${tag}" added!`)
    }

    return (
        <div className="ai-panel">
            {/* Header Toggle */}
            <button
                type="button"
                className="ai-panel-header"
                onClick={() => setIsOpen(!isOpen)}
                id="ai-panel-toggle"
            >
                <div className="ai-panel-title">
                    <span className="ai-icon">🤖</span>
                    <div>
                        <span className="ai-panel-name">AI Writing Assistant</span>
                        <span className="ai-badge-small">Powered by AI</span>
                    </div>
                </div>
                <span className={`ai-chevron ${isOpen ? 'open' : ''}`}>▼</span>
            </button>

            {/* Panel Content */}
            {isOpen && (
                <div className="ai-panel-body animate-slide-down">
                    {/* Mode Selector */}
                    <div className="ai-section">
                        <p className="ai-section-label">Improvement Mode</p>
                        <div className="ai-modes">
                            {AI_MODES.map(mode => (
                                <button
                                    key={mode.id}
                                    type="button"
                                    className={`ai-mode-btn ${activeMode === mode.id ? 'active' : ''}`}
                                    onClick={() => setActiveMode(mode.id)}
                                >
                                    <span className="mode-label">{mode.label}</span>
                                    <span className="mode-desc">{mode.desc}</span>
                                </button>
                            ))}
                        </div>
                        <button
                            type="button"
                            className="btn btn-primary"
                            onClick={handleImprove}
                            disabled={loadingImprove}
                            id="ai-improve-btn"
                        >
                            {loadingImprove ? <><span className="spinner" /> Processing...</> : '✨ Improve with AI'}
                        </button>
                    </div>

                    <div className="ai-divider" />

                    {/* Other AI Tools */}
                    <div className="ai-section">
                        <p className="ai-section-label">AI Tools</p>
                        <div className="ai-tools-grid">
                            <button
                                type="button"
                                className="ai-tool-btn"
                                onClick={handleSuggestTitle}
                                disabled={loadingTitle}
                                id="ai-title-btn"
                            >
                                {loadingTitle ? <div className="spinner" /> : '💡'}
                                <span>Title</span>
                            </button>
                            <button
                                type="button"
                                className="ai-tool-btn"
                                onClick={handleGenerateSummary}
                                disabled={loadingSummary}
                                id="ai-summary-btn"
                            >
                                {loadingSummary ? <div className="spinner" /> : '📋'}
                                <span>Summary</span>
                            </button>
                            <button
                                type="button"
                                className="ai-tool-btn"
                                onClick={handleSuggestTags}
                                disabled={loadingTags}
                                id="ai-tags-btn"
                            >
                                {loadingTags ? <div className="spinner" /> : '🏷️'}
                                <span>Tags</span>
                            </button>
                        </div>
                    </div>

                    {/* Tag Suggestions */}
                    {suggestedTags.length > 0 && (
                        <div className="ai-tags-section">
                            <p className="ai-section-label">Click to Add Tags</p>
                            <div className="ai-suggested-tags">
                                {suggestedTags.map(tag => (
                                    <button
                                        key={tag}
                                        type="button"
                                        className="ai-tag-pill"
                                        onClick={() => applyTag(tag)}
                                    >
                                        + {tag}
                                    </button>
                                ))}
                            </div>
                        </div>
                    )}

                    <p className="ai-disclaimer">
                        ⚠️ AI suggestions are automated. Review before publishing.
                    </p>
                </div>
            )}
        </div>
    )
}